name: Bug Report
description: Einen Bug melden.
title: "[Bug]: "
labels: ["bug"]
projects: ["HGLabor/6"]
body:
  - type: markdown
    attributes:
      value: |
        Danke das du dir die Zeit nimmst und einen Bug reportest. Sei bitte so genau wie möglich damit es uns leichter fällt den Bug nachzustellen.
  - type: dropdown
    id: client
    attributes:
      label: Welcher Client wurde verwendet?
      multiple: false
      options:
        - Unbekannt
        - NoRiskClient
        - Vanilla
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Beschreibe so genau wie möglich wie der Bug zustande kam.
      placeholder: Details!
      value: "Es gibt einen Bug wenn ....."
    validations:
      required: true
